# Generated by Django 3.1.7 on 2021-04-18 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('mobileNo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=200)),
                ('objectives', models.CharField(max_length=1000)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='UserInfo/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='UserInfo/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True, verbose_name='gender')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='Userprofile/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('job_location', models.CharField(max_length=50)),
                ('jobType', models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], max_length=50, null=True)),
                ('job_tags', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=1000)),
                ('application', models.URLField(max_length=100)),
                ('salary_per_month', models.IntegerField(default=0)),
                ('working_days', models.IntegerField(default=0)),
                ('apply_link', models.URLField(max_length=100)),
                ('deadline', models.DateField()),
                ('job_category', models.CharField(choices=[('Engineering', 'Engineering'), ('IT', 'IT'), ('Management', 'Management'), ('Sales', 'Sales'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Other', 'Other')], max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('company_website', models.URLField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('company_contact', models.CharField(max_length=20)),
                ('company_email', models.EmailField(max_length=30)),
                ('facebook_link', models.URLField(max_length=100)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='CompanyLogos/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatesApplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('mobileNo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JobFinder.jobpost')),
            ],
        ),
    ]
